// https://scalameta.org/scalafmt/docs/configuration.html
version = "3.10.7"
runner.dialect = scala213
align.preset = most
maxColumn = 160
project.git = true

continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = true

rewrite.rules = [SortImports, SortModifiers, RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
newlines.alwaysBeforeElseAfterCurlyIf = false

align.delayUntilSpace = false
align.tokens."+" = [
  { code = ":", owners = [{ regex = "Term\\.Param", parents = [ "Ctor\\.Primary" ] }, { parents = [ "Defn\\." ] }] },
  { code = "=" },
  { code = "=>", owners = [{ regex = "Case" }, { parents = ["Case"] }] },
  { code = "(", owners = [{ regex = "Case" }, { parents = ["Case"] }] },
  { code = ")", owners = [{ regex = "Case" }, { parents = ["Case"] }] },
  { code = ",", owners = [{ regex = "Case" }, { parents = ["Case"] }] }
]
align.arrowEnumeratorGenerator = true
assumeStandardLibraryStripMargin = true
align.stripMargin = true

docstrings.style = SpaceAsterisk
docstrings.oneline = fold
docstrings.wrap = no