name: Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Compile
        run: ./mill __.compile

      - name: Run Unit Test
        run: ./mill __.test

      - name: Run Integration Test
        run: ./mill --jobs 1 __.integrationTest
